services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - microestoque

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8006:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microestoque

    pgsql:
        image: 'postgres:13'
        ports:
            - '${FORWARD_DB_PORT:-5506}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
              - ".:/var/www/html"
        networks:
            - microestoque
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
            retries: 3
            timeout: 5s

    memcached:
        image: 'memcached:alpine'
        ports:
            - '11211:11211'
        networks:
            - microestoque

    # Serviço do MongoDB
    mongodb:
        image: mongo:latest
        container_name: laravel_mongo
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        networks:
            - microestoque

    # queue
    queue:
        image: especializati/laravel9-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - microestoque

    # redis
    redis:
        image: redis:latest
        networks:
            - microestoque

networks:
    microestoque:
        name: microestoque
        driver: bridge

volumes:
    mongodb_data:
        driver: local
